version: '3.2'
services:
  jenkins:
    build: .
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - ./src/casc.yaml:/var/jenkins_home/casc.yaml
    container_name: jenkins_demo
    env_file:
      - jks.env
