version: '3.2'
services:
  jenkins:
    build: .
    ports:
      - '7080:7080'
      - '40000:40000'
    volumes:
      - ./casc.yaml:/var/jenkins_home/casc.yaml
    container_name: jenkins_demo
    env_file:
      - jks.env
