version: '3.2'
services:
  jenkins:
    build: .
    ports:
      - '8080:8080'
      - '50000:50000'
    # volumes:
        # - jenkins-home:/var/jenkins_home
    container_name: jenkins
    env_file:
      - jks.env

volumes:
  jenkins-home:
